# site name
prefixName:
siteName: BestBonBai
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/avatar.jpg
url: https://sakura.bestbonbai.me
description: Live your life with passion! With some drive!
cdn: https://cdn.jsdelivr.net/gh/bestbonbai/bai_cdn@master
pjax: 1
# 1开启
mathjax: 0

notice: Welcome to my sakura studio...
lazyloadImg: https://cdn.jsdelivr.net/gh/bestbonbai/bai_cdn@master/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  Home: { path: /, fa: fa-fort-awesome faa-shake }
  Archive: { path: /archives, fa: fa-archive faa-shake, submenus: {
    tech: {path: /categories/tech/, fa: fa-code },
    live: {path: /categories/live/, fa: fa-file-text-o },
    source: {path: /categories/source/, fa: fa-cloud-download },
    think: {path: /categories/think/, fa: fa-commenting-o },
    refer: {path: /categories/refer/, fa: fa-book }
  } }
  list: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: {
    books: {path: /tags/books/, fa: fa-th-list faa-bounce },
    番组: {path: /bangumi/, fa: fa-film faa-vertical },
    music: {path: /music/, fa: fa-headphones },
    photos: {path: /tags/photos/, fa: fa-photo }
  } }
  comment: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  friends: { path: /links/, fa: fa-link faa-shake }
  donate: { path: /donate/, fa: fa-heart faa-pulse }
  about: { path: /, fa: fa-leaf faa-wrench , submenus: {
    me？: {path: /about/, fa: fa-meetup},
    theme: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  APP: { path: /client/, fa: fa-android faa-vertical }
  # RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/bestbonbai/bai_cdn@master/img/cover/(1).jpg.webp
  - https://cdn.jsdelivr.net/gh/bestbonbai/bai_cdn@master/img/cover/(2).jpg.webp
  - https://cdn.jsdelivr.net/gh/bestbonbai/bai_cdn@master/img/cover/(3).jpg.webp
  - https://cdn.jsdelivr.net/gh/bestbonbai/bai_cdn@master/img/cover/(4).jpg.webp
  - https://cdn.jsdelivr.net/gh/bestbonbai/bai_cdn@master/img/cover/(5).jpg.webp
  - https://cdn.jsdelivr.net/gh/bestbonbai/bai_cdn@master/img/cover/(6).jpg.webp
  - https://cdn.jsdelivr.net/gh/bestbonbai/bai_cdn@master/img/cover/(7).jpg.webp
  - https://cdn.jsdelivr.net/gh/bestbonbai/bai_cdn@master/img/cover/(8).jpg.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dim

# startdash url, title, desc img
startdash:
  - {url: /theme-sakura/, title: Sakura, desc: Powered by hexo, img: /img/startdash/sakura.md.png}
  # - {url: http://space.bilibili.com/271849279, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
  - {url: /, title: BestBonBai's Sakura Studio, desc: personal blogs, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 01/19/2021

#social  url, img PC端配置
social:
  github: {url: https://github.com/BestBonBai, img: /img/social/github.png}
  # sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  # wangyiyun: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/wangyiyun.png}
  # zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/zhihu.png}
  email: {url: mailto:jsbaihualin@hotmail.com, img: /img/social/email.svg}
  facebook: {url: https://facebook.com/barry.bai.315, img: /img/social/facebook.png}
  # wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
  # wechat2: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/BestBonBai, fa: fa-github, color: 333}
  # weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  # qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  # paypal: https://www.paypal.me/hojuncn
  # alipay: /img/custom/donate/AliPayQR.jpg
  wechat: /img/custom/donate/WeChanQR.png
  wechatSQ: /img/custom/donate/WeChanQR.png

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  switch: false
  # url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  # name: Unbroken.mp4

aplayer:
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# for SEO
seo:
  description: BestBonBai's Sakura Studio
  keywords: bestbonbai, hexo, studio, github, sakura

#  页脚显示网站运行时间
runtime: true

# Valine
valine: true
v_appId: jkcm9jGblUTBarpWSiMeQ6ku-MdYXbMMI
v_appKey: twGl2qQIqSDAEVeTVJF2yyT0

# 页脚信息 支持HTML标记
pagefooter: Copyright of @BestBonBai.me
